### ISSUE TITLE
AAAA record and IPv4/IPv6 providers

### ISSUE THREAD

**Issue by fagnercarvalho** [headincloud/cf-ddns-agent#5]
First of all, this looks awesome! Thank you for making this available.

I just migrated one of my domains (and I plan to migrate another one) to Cloudflare and I was using https://github.com/timothymiller/cloudflare-ddns for DDNS however I was looking for one made in Go.

This library is using ``https://1.1.1.1/cdn-cgi/trace`` and `https://[2606:4700:4700::1111]/cdn-cgi/trace` (or http://dns64.cloudflare-dns.com/cdn-cgi/trace) for IPv4 and IPv6, respectively. This seems to be reliable but the parsing is a little more tricky since there is additional information returned from these endpoints.

Those addresses are also used in the most starred DDNS clients (https://github.com/troglobit/inadyn/tree/master/examples) here in GitHub.

If you want I can go ahead and make a PR to use the two addresses to resolve the IPs and update it in Cloudflare on top of the current provider.

Thanks!

**Comment by jeroenjacobs79** [comment]
Thanks for the suggestion :)

The problem with IPv6 discovery, is that different addresses might be used for inbound and outbound connections (due to IPv6 Privacy Extensions, which generate a temporary address for outbound connections). 

I assume most people use dynamic DNS for easy inbound connections, so the outbound address (which is returned by a remote discovery site)  is of no use.

I'm currently testing some code that hopefully discovers the correct IPv6 address by parsing some properties of the IPv6 addresses as returned by the operating system. Will have more info in the next few days.

**Comment by jeroenjacobs79** [comment]
At the moment, there is no way in Go to distinguish between the real and temporary IPv6 address. I have created a proposal for this in the past, but it hasn't been picked up so far: https://github.com/golang/go/issues/42694

I will add support for IPv6 via remote discovery this week, however, this means that you will probably need to disable ipv6 privacy extensions on your adapter.

New version will probably be released by end of the week.

**Comment by fagner-koho** [comment]
Thank you for the fast reply!

I will admit I never heard about this before. I will read the RFC.

I'm looking forward for the next version!

**Comment by fagnercarvalho** [comment]
Thank you for the fast reply!

I will admit I never heard about this before. I will read the RFC.

I'm looking forward for the next version!

**Comment by jeroenjacobs79** [comment]
@fagnercarvalho Better late than never, but I just released a new version with experimental ipv6 support ;)
